/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as MegahairRouteImport } from './routes/megahair'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnhasRouteImport } from './routes/unhas'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const MegahairRoute = MegahairRouteImport.update({
  id: '/megahair',
  path: '/megahair',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnhasRoute = UnhasRouteImport.update({
  id: '/unhas',
  path: '/unhas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/megahair': typeof MegahairRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unhas': typeof UnhasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/megahair': typeof MegahairRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unhas': typeof UnhasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/avaliar': typeof AvaliarRoute
  '/megahair': typeof MegahairRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unhas': typeof UnhasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/avaliar'
    | '/megahair'
    | '/sitemap.xml'
    | '/unhas'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/avaliar'
    | '/megahair'
    | '/sitemap.xml'
    | '/unhas'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/avaliar'
    | '/megahair'
    | '/sitemap.xml'
    | '/unhas'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvaliarRoute: typeof AvaliarRoute
  MegahairRoute: typeof MegahairRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnhasRoute: typeof UnhasRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/megahair': {
      id: '/megahair'
      path: '/megahair'
      fullPath: '/megahair'
      preLoaderRoute: typeof MegahairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unhas': {
      id: '/unhas'
      path: '/unhas'
      fullPath: '/unhas'
      preLoaderRoute: typeof UnhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvaliarRoute: AvaliarRoute,
  MegahairRoute: MegahairRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnhasRoute: UnhasRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
